services:
  api:
    build: app
    environment:
      DATABASE_URL: postgresql+psycopg2://rbem:supersecure123@db:5432/analytics
      OLLAMA_BASE_URL: http://host.docker.internal:11435
    ports:
      - "8000:8000"
    depends_on:
      db: 
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - llama_index_default

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rbem
      POSTGRES_PASSWORD: supersecure123
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  llama_index_default:
    external: true
    