services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.3.7
    environment:
      - ENV=PROD
      - ENABLE_COMMUNITY_SHARING=False
      - USE_CUDA_DOCKER=False
      - GLOBAL_LOG_LEVEL=INFO
    ports:
      - "3030:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:cuda
    environment:
      - PIPELINES_URLS=file:///app/pipelines/llama_index_retrieval_pipeline.py
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ./pipelines/llama_index_retrieval_pipeline.py
        target: /app/pipelines/llama_index_retrieval_pipeline.py

      - type: bind
        source: ./persist
        target: /app/persist

      - pipelines:/app/pipelines
    restart: unless-stopped

volumes:
  open-webui:
  pipelines:
