name: LaTeX Build

on:
  push:
    branches: [ "master" ]
    tags-ignore: [ "*" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-

      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tectonic
        run: |
          cd undergrad-thesis
          tectonic -X compile --keep-intermediates main.tex -Zshell-escape
          mv main.pdf ../main.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main
          path: main.pdf
